stages:
  - build
  - deploy

default:
  image: google/cloud-sdk:alpine
  before_script:
    - gcloud auth activate-service-account --key-file $K8S_DEPLOYER
    - gcloud config set project $K8S_PROJECT_ID

build:
  stage: build
  script:
    - |
      gcloud builds submit  \
        --config=cloudbuild.yaml \
        --substitutions=_VERSION=$CI_COMMIT_REF_SLUG,_IMAGE=gcr.io/excellent-nexus-271309/pdf

deploy:
  stage: deploy
  only:
    - master
  dependencies:
    - build
  script:
    - |
      gcloud builds submit \
        --config=clouddeploy.yaml \
        --substitutions=_VERSION=$CI_COMMIT_REF_SLUG,_IMAGE=gcr.io/excellent-nexus-271309/pdf,_ENV=production
