steps:
  - name: docker
    args:
      - pull
      - $_IMAGE:latest
  - name: docker
    args:
      - build
      - -t
      - $_IMAGE:$_VERSION
      - --cache-from
      - $_IMAGE:latest
      - .
  - name: docker
    args:
      - tag
      - $_IMAGE:$_VERSION
      - $_IMAGE:latest
images:
  - $_IMAGE:$_VERSION
  - $_IMAGE:latest
