version: '3'

services:
  app:
    build: .
    command: npm run start:debug
    volumes:
      - ./:/var/app
      - ./google-key.json:/google/key.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /google/key.json
    ports:
      - 5000:5000
      - 9229:9229
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
