version: '3'

services:
  app:
    build: .
    command: npm run start:debug
    volumes:
      - ./:/var/app
    ports:
      - 5000:5000
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
